name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: aryanet
          config_timezone: Americal/Los_Angeles
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          config_order: base.header, isocalendar, languages, stars
          config_output: insights
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          use_prebuilt_image: yes
          
          
